var jQuerySlideshow1_json = 
	{
 "innernavbar.hideOnMouseOut": false,
 "innerthumbscroll.hideOnMouseOut": false,
 "innerbullets_next.opacity": "1",
 "innernumbers_next.halign": "left",
 "backgroundType": "normal",
 "resumeDuration": "3000",
 "innercurrentslide.slideEffect": "fadeIn",
 "innernumbers.valign": "middle",
 "innersubcaption.useSlideEffect": false,
 "innercaption.mouseOutEffectDelay": "0",
 "innercurrentslide.mouseOutEffectEasing": "linear",
 "tooltip.backgroundType": "normal",
 "innercaption_back.halign": "center",
 "innerplaypause.valign": "middle",
 "innerbutton.next.hideOnMouseOut": true,
 "innerplaypause.mouseOutEffect": "fadeIn",
 "innerthumbscroll.mouseOutEffect": "fadeIn",
 "innerthumbscroll.halign": "left",
 "innerthumbscroll.scrollerOrientation": "horizontal",
 "innerbutton.back.hideOnMouseOut": true,
 "innerplaypause.opacity": 1,
 "innerthumbscroll.mouseOutEffectEasing": "swing",
 "innerthumbscrollitemthumb.hover.mouseOverEffect": false,
 "innerbulletsitem.spacing": "10px",
 "innerthumbscrollitem.hover.backgroundType": "normal",
 "innerbutton.back.halign": "center",
 "innersubcaption.top": "60px",
 "innerplaypause.mouseOutEffectEasing": "linear",
 "innernavbar_back.opacity": "1",
 "innernavbar.mouseOutEffectDuration": "1000",
 "navbar_next.opacity": "1",
 "innernumbers.mouseOutEffectEasing": "linear",
 "innercaption.halign": "left",
 "innernavbar.orientation": "horizontal",
 "innerthumbscrollitem.spacing": "0px",
 "innerbullets.mouseOutEffectDuration": "500",
 "innercurrentslide.mouseOutEffect": "fadeIn",
 "tooltip.speed": "500",
 "caption.opacity": "1",
 "innernavbaritem.spacing": "0px",
 "innernumbers_back.halign": "left",
 "innersubcaption_back.valign": "middle",
 "continuous": true,
 "innernumbers.scrollerOrientation": "horizontal",
 "innernumbers.halign": "left",
 "innerthumbscroll.valign": "bottom",
 "innernavbar.valign": "top",
 "innerthumbscrollitemthumb.hover.opacity": "1",
 "preloading": "includes/jQuerySlideshow/preloading.gif",
 "innercurrentslide.valign": "top",
 "innersubcaption.width": "150px",
 "innernumbers_next.valign": "top",
 "innersubcaption.slideEffectEasing": "easeOut",
 "innerbullets.hideOnMouseOut": false,
 "innernavbaritem.contentType": "image & text to right",
 "relPath": "",
 "innersubcaption.slideEffect": "slideFromLeft",
 "innerbutton.next.top": "0px",
 "innercaption_back.top": "0px",
 "innercurrentslide.hideOnMouseOut": false,
 "innerthumbscroll.backgroundType": "normal",
 "innerbutton.back.valign": "middle",
 "fadeDuration": "500",
 "innerplaypause.hideOnMouseOut": false,
 "innernavbaritemthumb.hover.opacity": "1",
 "innerthumbscrollitem.backgroundType": "normal",
 "tooltip.easing": "easeOut",
 "innercaption.left": "0px",
 "innerbullets.backgroundType": "normal",
 "innerbutton.back.mouseOutEffect": "fadeIn",
 "innersubcaption_back.left": "0px",
 "thumbscroll_next.opacity": "1",
 "innerplaypause.left": "-328px",
 "innercaption_next.top": "0px",
 "innerthumbscrollitem.active.backgroundType": "normal",
 "innerbullets.scrollerOrientation": "vertical",
 "innerbutton.next.mouseOutEffect": "fadeIn",
 "innernumbers.spacing": "0px",
 "innercaption.opacity": "0.65",
 "tooltip.side": "right",
 "innersubcaption.left": "0px",
 "sliderEffect": "slide",
 "innernavbaritemthumb.hover.mouseOverEffectEasing": "linear",
 "innernumbers.left": "40px",
 "innersubcaption.halign": "left",
 "innerbulletsitem.orientation": "vertical",
 "innercaption.slideEffect": "slideFromLeft",
 "innerbulletsitem.hover.backgroundType": "normal",
 "innercaption_next.left": "0px",
 "innernumbers_back.valign": "top",
 "innerbulletsitem.active.backgroundType": "normal",
 "innernumbers.mouseOutEffectDuration": "1000",
 "innerthumbscrollitem.height": "65px",
 "effect": "boxRain",
 "innernavbar.mouseOutEffect": "fadeIn",
 "innernumbers.scrollerType": "noScroll",
 "innernumbers_next.left": "0px",
 "innernavbar.left": "0px",
 "innercurrentslide.left": "0px",
 "innerbullets.left": "0px",
 "innerbutton.next.left": "25px",
 "innerthumbscroll.mouseOutEffectDuration": "400",
 "innerthumbscroll.left": "5px",
 "innersubcaption.mouseOutEffect": "slideFromLeft",
 "innernavbar.scrollerOrientation": "horizontal",
 "tooltip.show": true,
 "width": "700px",
 "innerbullets.width": "10px",
 "height": "300px",
 "innerbutton.back.left": "-342px",
 "innerslider.top": "0px",
 "innercaption.hideOnMouseOut": true,
 "innernavbar_next.opacity": "1",
 "innernavbaritemthumb.hover.mouseOverEffectDuration": "2000",
 "innersubcaption.hideOnMouseOut": true,
 "innersubcaption_back.top": "0px",
 "thumbscroll_back.opacity": "1",
 "innerthumbscroll.orientation": "horizontal",
 "innercaption_back.valign": "middle",
 "innernavbar.mouseOutEffectEasing": "linear",
 "subcaption.opacity": "1",
 "innerthumbscroll.scrollerType": "noScroll",
 "innercaption.useSlideEffect": false,
 "innerbullets.valign": "top",
 "innerplaypause.mouseOutEffectDuration": "1000",
 "innerthumbscrollitemthumb.opacity": "1",
 "thumbscrollitem.orientation": "horizontal",
 "ease": "easeOut",
 "innerbutton.next.halign": "right",
 "innercurrentslide.slideEffectEasing": "linear",
 "pauseTime": "3000",
 "innerbullets.mouseOutEffect": "slideFromBottom",
 "thumbscroll.scrollerOrientation": "horizontal",
 "innercaption.mouseOutEffectDuration": "1000",
 "innernumbers.hideOnMouseOut": false,
 "innernumbers_back.left": "0px",
 "align": "left",
 "innernavbaritemthumb.hover.mouseOverEffect": false,
 "innerbullets.orientation": "vertical",
 "innercaption.mouseOutEffect": "slideFromLeft",
 "innerbutton.next.mouseOutEffectDuration": "200",
 "innernavbar.top": "0px",
 "tooltip.offsX": "10px",
 "innerimagearea.left": "0px",
 "innerbutton.back.top": "0px",
 "innernumbersitem.orientation": "horizontal",
 "innerbutton.back.mouseOutEffectDuration": "200",
 "innernumbers_next.top": "0px",
 "innersubcaption_next.left": "0px",
 "innerthumbscroll.width": "594px",
 "tooltip.reverseSide": false,
 "innernumbers.orientation": "horizontal",
 "innerplaypause.top": "130px",
 "innerbullets.top": "0px",
 "innerslider.left": "0px",
 "innercurrentslide.top": "0px",
 "innernavbaritemthumb.active.opacity": "1",
 "innerthumbscroll.top": "-1px",
 "innercurrentslide.mouseOutEffectDuration": "1000",
 "innerthumbscroll.height": "57px",
 "innercaption.slideEffectEasing": "easeOut",
 "innercaption.top": "0px",
 "innersubcaption.height": "240px",
 "innerthumbscrollitem.width": "88px",
 "innersubcaption.mouseOutEffectDelay": "0",
 "innerplaypause.halign": "center",
 "innersubcaption_next.halign": "center",
 "tooltip.offsY": "-40px",
 "innersubcaption_back.halign": "center",
 "innercaption.height": "280px",
 "innernavbar.halign": "left",
 "speed": "500",
 "innerimagearea.top": "0px",
 "innernavbar.scrollerType": "noScroll",
 "innersubcaption.opacity": "1",
 "innerthumbscrollitemthumb.active.opacity": "1",
 "imagearea.top": "0px",
 "innerthumbscroll_next.opacity": "1",
 "innersubcaption_next.top": "0px",
 "vertical": false,
 "innersubcaption.mouseOutEffectEasing": "easeOut",
 "innerbullets.halign": "right",
 "imagearea.left": "0px",
 "innernumbers_back.top": "0px",
 "innernumbers_back.opacity": "1",
 "pause": "1000",
 "innercurrentslide.halign": "left",
 "innerthumbscrollitem.orientation": "horizontal",
 "innerbullets_back.opacity": "1",
 "innerbutton.next.opacity": 1,
 "innersubcaption.valign": "top",
 "stopAtInteraction": false,
 "auto": true,
 "innerbullets.mouseOutEffectEasing": "linear",
 "innernumbers.mouseOutEffect": "fadeIn",
 "innerbutton.back.opacity": 1,
 "innerbutton.next.valign": "middle",
 "innernavbaritemthumb.opacity": "1",
 "innerbullets.opacity": "0.6",
 "currentslide.opacity": "1",
 "innerthumbscroll_back.opacity": "1",
 "innerthumbscrollitemthumb.hover.mouseOverEffectEasing": "linear",
 "innerbutton.next.mouseOutEffectEasing": "linear",
 "innernavbaritem.orientation": "horizontal",
 "innerbulletsitem.backgroundType": "normal",
 "innercaption.valign": "top",
 "innercaption_next.halign": "center",
 "innercaption_next.valign": "middle",
 "innerbutton.back.mouseOutEffectEasing": "linear",
 "innercaption_back.left": "0px",
 "hideOnMouseOut": true,
 "innercaption.width": "150px",
 "gifPath": "includes/jQuerySlideshow/x.gif",
 "loop": true,
 "innercurrentslide.opacity": "1",
 "navbar_back.opacity": "1",
 "innersubcaption_next.valign": "middle",
 "tooltip.width": "200px",
 "innerthumbscroll.itemWidth": "95px",
 "tooltip.height": "70px",
 "innerthumbscroll.itemHeight": "65px",
 "innercaption.mouseOutEffectEasing": "easeOut",
 "innerbullets.height": "290px",
 "innerthumbscrollitemthumb.hover.mouseOverEffectDuration": "2000",
 "innernumbers_next.opacity": "1",
 "innersubcaption.mouseOutEffectDuration": "1000"
};


var jQuerySlideshow1_source = [{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/212032lflf1gqflxhctodx.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2238271zu8do8uduzdu0ou.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22383499g7p8jj90zjjpcw.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223845qs7jpwxe1jepzzuf.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223852sp59u9164ucky69c.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223901jllljlfgblo2ibp0.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223910ks1ssxuw4smqx6o4.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223918666ttyonnnyqtzic.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223924egvlemewho9s9ugl.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223930eqewttttcqpp8scw.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223935tb2frwewaek9kbar.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223943bpcqmqzampbw1zub.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223951jflh89dvhf2ffdl6.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2239585s0uuavmzsb05zq9.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224020xj2u7yz7xlppaeop.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2240255m58s8lskyv5v6s6.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224032yzy3yaydje3t753k.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224039320359nyzwk20usm.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224046z06cssc0zvdzcl10.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224053a802jupibtu1n1js.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2241009dq3angqdnpn9hp8.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22410809zlw8w70828o8w9.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224114fvdwf883fz63vuss.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22412405pw5q7coyzthc7h.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2241334hsh99agzas45tf4.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224140o4zffo8zpuncahpq.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224150gs547bu5bfqu0cf0.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224159p30i7w0ozrjjzgao.jpg","link":"","title":""},{"target":"_self","description":"","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224205rbtzb99bh6yt06y6.jpg","link":"","title":""}];
var jQuerySlideshow1_tooltipsource = [{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/212032lflf1gqflxhctodxtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2238271zu8do8uduzdu0outooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22383499g7p8jj90zjjpcwtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223845qs7jpwxe1jepzzuftooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223852sp59u9164ucky69ctooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223901jllljlfgblo2ibp0tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223910ks1ssxuw4smqx6o4tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223918666ttyonnnyqtzictooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223924egvlemewho9s9ugltooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223930eqewttttcqpp8scwtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223935tb2frwewaek9kbartooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223943bpcqmqzampbw1zubtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/223951jflh89dvhf2ffdl6tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2239585s0uuavmzsb05zq9tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224020xj2u7yz7xlppaeoptooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2240255m58s8lskyv5v6s6tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224032yzy3yaydje3t753ktooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224039320359nyzwk20usmtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224046z06cssc0zvdzcl10tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224053a802jupibtu1n1jstooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2241009dq3angqdnpn9hp8tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22410809zlw8w70828o8w9tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224114fvdwf883fz63vusstooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/22412405pw5q7coyzthc7htooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/2241334hsh99agzas45tf4tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224140o4zffo8zpuncahpqtooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224150gs547bu5bfqu0cf0tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224159p30i7w0ozrjjzgaotooltip.jpg"},{"src":"includes/jQuerySlideshow/images/jQuerySlideshow1/224205rbtzb99bh6yt06y6tooltip.jpg"}];
var jQuerySlideshow1_slideshow = null;	

xtd_jQuerySlideshow(document).ready(function(){
	var $ = xtd_jQuerySlideshow;
	var jQuery = xtd_jQuerySlideshow;
	
	$("#jQuerySlideshow1Container").hide();
	
	// fix bug on webkit//
	if (jQuery.browser.webkit && document.readyState != "complete") {
		setTimeout( createJQuerySlideShow, 100 );
	} else {
		createJQuerySlideShow()
	}
		
	function createJQuerySlideShow() {

		if (document.readyState && document.readyState != "complete") {
			setTimeout( createJQuerySlideShow, 100 );
			return;
		}

		//show element first as height/width of auto elements is 0 if container is hidden//
		$("#jQuerySlideshow1Container").show();
		
		// create the slider
		jQuerySlideshow1_slideshow = $("#jQuerySlideshow1").jQuerySlideShow();
	}
});